version: '3.8'

services:
  server:
    image: ${DOCKER_USERNAME}/my-mern-backend:latest
    container_name: backend-server
    ports:
      - "3010:3010"
    environment:
      - PORT=3010
      - MONGO=mongodb+srv://Roshan:Roshan@mern.f4ucev3.mongodb.net/Mern-Project?retryWrites=true&w=majority&appName=Mern
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped
